### ISSUE TITLE
PUT /users/ returns 500 Internal Server Error

### ISSUE THREAD

**Issue by llorepriest** [yudjinn/nwbnk-api#10]
Sent {"username":"TestUser","in_game_name":"Tester","discord_name":null,"discord_id":null,"is_active":true,"is_superuser":false,"company_id":null,"rank":2,"id":"1649713c-188d-11ec-b2bc-a66fd67cf71c","updated_dt":"2021-09-18T14:31:18.501030","created_dt":"2021-09-18T14:31:18.501036"}

**Comment by llorepriest** [comment]
Actually, when I posted the other issue about CORS I realized the call to the company api also had the CORS headers missing on the POST.

**Comment by yudjinn** [comment]
resolved by #12
