### ISSUE TITLE
POST to /company/{company_id}/{user_id}/{rank} generating Error 500

### ISSUE THREAD

**Issue by llorepriest** [yudjinn/nwbnk-api#16]
I believe this was working yesterday, but appears to be blowing up again. I was attemtping to post

https://stage-nwbnk-api.herokuapp.com/api/v1/company/f696fc2e-17e7-11ec-a357-ce83fd8a66bc/3c19b020-19af-11ec-b536-62d8734d42ff/1

**Comment by yudjinn** [comment]
Is this the resolved issue with updating the user?
